### ISSUE TITLE
Table should be object extends null

### ISSUE THREAD

**Issue by LongTengDao** [iarna/iarna-toml#11]
```toml
toString = 1
```

This will cause an error:

```
Can't redefine existing key
```

There is two way to fix this,

1.  use `hasOwnProperty`, not `in`
2.  use `Object.create(null)` to create a table, not `{}`

But the first way is slow, and can't deal with `__proto__` property, so the way 2 is better.

**Comment by iarna** [comment]
Alternatively, I could use `Map` objects… 🤔 OTOH, as this is in some ways a stand in for JSON.parse and JSON.stringify, plain objects seem less surprising.

**Comment by iarna** [comment]
Seeing as `JSON.parse` does uses plain objects (eg `JSON.parse('{"a": 1}').toString()` is valid), I'm inclined toward the `hasOwnProperty` route, for all its disadvantages.

**Comment by iarna** [comment]
A quick check shows the `hasOwnProperty` variation doesn't have an impact on our benchmarks, so I'm going to go with that.

**Comment by LongTengDao** [comment]
In consideration of that TOML is a config format, it will usually be parsed only one time, the disadvantage of speed is acceptable. 🤝 @iarna

**Comment by iarna** [comment]
Also, as I say, it doesn't actually impact speed on real-world datasets. (I load very very large sets of TOML, so speed does matter a lot to me. On the order of 126MB at a time.)
