### ISSUE TITLE
TOML.parse throws on some hex literals containing the character E/e

### ISSUE THREAD

**Issue by ghost** [iarna/iarna-toml#20]
Simple test cases:
```javascript
TOML.parse("hex = 0xe");   // Throws
TOML.parse("hex = 0x0e");  // Works

TOML.parse("hex = 0x0_e"); // Throws
TOML.parse("hex = 0x0_f"); // Works
```

The issue seems to be caused by `.parseNoUnder()` being re-used for hex literals and not being hex character aware.

**Comment by iarna** [comment]
Reopening this as the tests don't test the error condition (they pass without the patch) and they don't produce full coverage (they don't exercise the error conditions.
![image](https://user-images.githubusercontent.com/983798/79804151-4e0ab600-8318-11ea-912f-3b4f45ef54a4.png)

**Comment by iarna** [comment]
Specifically, the tests worked on older versions because only lower case Es produced this error. Capital Es, as found in the test, worked fine.

**Comment by iarna** [comment]
(I'm going to be kind of stream-of-consciousnessing into this issue while I get this fixed up and published, so please don't take my babbling here as a call to do something.)

**Comment by iarna** [comment]
My update to the original tests was to make it just match this here directly:

https://github.com/iarna/iarna-toml/commit/cec9c4ec8bdcecc2e6fbdb1f4da2986fe4693ddf

My additional tests to reach 100% test coverage are here:

https://github.com/iarna/iarna-toml/commit/c7e08cb3a753f24f7cab00ac54475743ef1ab3a3
