### ISSUE TITLE
TOML v1.0.0-rc.1 Support

### ISSUE THREAD

**Issue by 0az** [iarna/iarna-toml#24]
As of last week, there's now a RC for 1.0.

[Changes][release]:

> - Clarify in ABNF how quotes in multi-line basic and multi-line literal strings
> - are allowed to be used.
> - Leading zeroes in exponent parts of floats are permitted.
> - Clarify that control characters are not permitted in comments.
> - Clarify behavior of tables defined implicitly by dotted keys.
> - Clarify that inline tables are immutable.
> - Clarify that trailing commas are not allowed in inline tables.
> - Clarify in ABNF that UTF-16 surrogate code points (U+D800 - U+DFFF) are not
> - allowed in strings or comments.
> - Allow raw tab characters in basic strings and multi-line basic strings.
> - Allow heterogenous values in arrays.

[release]: https://github.com/toml-lang/toml/releases/tag/v1.0.0-rc.1

I don't want to *commit* to doing this, but I *might* be able to find time... eventually. :)

**Comment by iarna** [comment]
The place to start for this will be making tests over in https://github.com/iarna/toml-spec-tests

That'll make clear what changes actually need to be made over here.

**Comment by iarna** [comment]
I've started adding tests over there -- I'll update over here if I wrap up, but the repo should remain up to date as I work.

**Comment by iarna** [comment]
> * Allow heterogenous values in arrays.

Wow that's a big change!!

**Comment by iarna** [comment]
The spec tests have now been updated based on the changes to the English specification document. Currently there are definitely some corner cases represented in the changelog (and the ABNF doc) that are not covered.

Remaining:
1. Updating this module to pass the current tests.
2. Updating the spec tests based on the other sources of truth (eg, changelog, and a methodical reading of the ABNF).

**Comment by iarna** [comment]
Ok, updated spec tests are here:

https://github.com/iarna/toml-spec-tests/tree/1.0.0-rc.1

Updates for this module are here:

https://github.com/iarna/iarna-toml/tree/spec-1-0-rc-1

Everything seems to be in order. I'll likely sit on this for a day or two before publishing something. Updates to the doc comparing module compliance is here:

https://shared.by.re-becca.org/misc/TOML-SPEC-SUPPORT-v1.html

**Comment by iarna** [comment]
Published as: https://www.npmjs.com/package/@iarna/toml/v/3.0.0
