### ISSUE TITLE
How to 'merge' toml files 

### ISSUE THREAD

**Issue by akkumar** [iarna/iarna-toml#27]
I have an application with a default set of options and another set of options to override the default (either the subset or its entirety ) . How do pass 2 .toml in a specific order so I get a final object that represents the merged / overridden values. 

Eg: 

Eg: default.toml 
```default.toml
[db]
readURI = "mysql://user:pass@127.0.0.1/mydb?charset=utf8"
writeURI = "mysql://user:pass@127.0.0.1/mydb?charset=utf8"

[db.options]
ConnMaxLifetime = 1
MaxOpenConns = 10
```

Eg: prod.toml
```prod.toml
[db]
readURI = "mysql://secureuser:securepass@127.0.0.1/mydb?charset=utf8"
writeURI = "mysql://secureuser:securepass@127.0.0.1/mydb?charset=utf8"
```

So hypothetically an api like -
```node
parser.parse(['default.toml',' prod.toml']
```

would yield a final toml object as below:

```final.toml
[db]
readURI = "mysql://secureuser:securepass@127.0.0.1/mydb?charset=utf8"
writeURI = "mysql://secureuser:securepass@127.0.0.1/mydb?charset=utf8"

[db.options]
ConnMaxLifetime = 1
MaxOpenConns = 10
```

Eg:  the go implementation takes in an object and 'decodes' a given toml on that object. This helps us to have a simpler override functionality.  More details at https://godoc.org/github.com/BurntSushi/toml#Decode . 

Is there a similar api / hack available to repeatedly parse and process a bunch of .toml files so we can override default options ?

**Comment by iarna** [comment]
@akkumar So the result of `TOML.parse` is just a JS object, so the usual approach would be to combine them with JS tools. Exactly what that looks like depends on your needs:

So you might go with the most simple option, with object composition:

```js
const default = TOML.parse(default)
const prod = TOML.parse(prod)
const config = {...default, ...prod}
```

Or use a module for deep merging: (not an endorsement of this particular module, it's just what came up when searching)

```js
const objectMerge = require('object-merge')
const default = TOML.parse(default)
const prod = TOML.parse(prod)
const config = objectMerge(default , prod)
```

Both of these methods can merge as many objects together as you like.

**Comment by iarna** [comment]
Something that might be cool would be a config library built on top of this library that provides composition of objects like this. Maybe something like [`rc`](https://www.npmjs.com/package/rc) but built on TOML instead of ini files.
